-- Insert sample video data
INSERT INTO videos (
  id,
  user_id,
  title,
  description,
  video_url,
  thumbnail_url,
  music,
  hashtags,
  like_count,
  view_count,
  comment_count,
  shares,
  privacy_level
) VALUES 
(
  gen_random_uuid(),
  (SELECT id FROM profiles ORDER BY created_at DESC LIMIT 1),
  'Amazing Dance Tutorial',
  'Learning this new dance trend! What do you think? 💃 #dance #viral #fyp #shetalks',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=600&fit=crop',
  '♪ Dance Monkey - Tones and I',
  ARRAY['dance', 'viral', 'fyp', 'shetalks'],
  1240,
  8500,
  89,
  23,
  'public'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles ORDER BY created_at DESC LIMIT 1 OFFSET 1),
  'Perfect Pasta Recipe',
  'Making the perfect pasta from scratch 🍝 Recipe in comments! #cooking #foodie #shetalks',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=600&fit=crop',
  '♪ Cooking Time - Original Sound',
  ARRAY['cooking', 'foodie', 'shetalks'],
  890,
  5200,
  44,
  17,
  'public'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles ORDER BY created_at DESC LIMIT 1 OFFSET 2),
  'Speed Painting Sunset',
  'Painting this sunset in 60 seconds ⏰🎨 #speedpaint #art #sunset #creative #shetalks',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&h=600&fit=crop',
  '♪ Peaceful Vibes - Chill Mix',
  ARRAY['speedpaint', 'art', 'sunset', 'creative', 'shetalks'],
  1520,
  12000,
  120,
  45,
  'public'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles ORDER BY created_at DESC LIMIT 1 OFFSET 3),
  'iPhone Tips & Tricks',
  'Mind-blowing iPhone tricks you didn''t know! 📱✨ #techtips #iphone #lifehacks #shetalks',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
  'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=600&fit=crop',
  '♪ Tech Vibes - Electronic Beat',
  ARRAY['techtips', 'iphone', 'lifehacks', 'shetalks'],
  2210,
  18500,
  187,
  89,
  'public'
),
(
  gen_random_uuid(),
  (SELECT id FROM profiles ORDER BY created_at DESC LIMIT 1 OFFSET 4),
  'Morning Workout Routine',
  '5-minute morning workout routine! No equipment needed 💪 #fitness #morning #workout #shetalks',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
  'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop',
  '♪ Pump It Up - Workout Mix',
  ARRAY['fitness', 'morning', 'workout', 'shetalks'],
  980,
  6800,
  62,
  28,
  'public'
) ON CONFLICT (id) DO NOTHING;