// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Use environment variables if available, otherwise fallback to default values
const url = SUPABASE_URL || "https://xokezxcubfffhwxmceby.supabase.co";
const key = SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhva2V6eGN1YmZmZmh3eG1jZWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzg1MDUsImV4cCI6MjA2NzE1NDUwNX0.aX0nGZ_sBJh1bjs-dy2Br1CL_93iNcajZFLoTkECcOA";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn('Using fallback Supabase configuration. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});